### ISSUE TITLE
Can you provide semi-supervised learning eval codes?

### ISSUE THREAD

**Issue by gyfastas** [salesforce/PCL#12]
Great work! I noticed that the semi-supervised classification evaluation result was shown in the paper. Can you provide a config file or a python script for reproducing the result?

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest! You can reference this code to set-up low-resource fine-tuning on ImageNet: 
https://github.com/salesforce/MoPro/blob/master/finetune_imagenet.py
