### ISSUE TITLE
Imbalanced datasets

### ISSUE THREAD

**Issue by millanp95** [salesforce/PCL#15]
Hi, 

Thank you for this implementation. It is my understanding that some contrastive frameworks build upon entropy maximization which leads to inapplicability in the contexts of imbalanced datasets. I don't see the direct connection between the ProtoNCE loss and the entropy so I was wondering,  does this method support imbalanced datasets? 

Thanks

**Comment by LiJunnan1992** [comment]
Hi, thanks for your question.

ProtoNCE should be able to support imbalanced datasets, since it is an unsupervised learning method which is unaware of the class distribution.
