### ISSUE TITLE
The training time of PCL?

### ISSUE THREAD

**Issue by zwzhang123** [salesforce/PCL#2]
Hi, I want to know the training time of PCL on each data set, ImageNet & VOC. And the type of graphics card. Thanks.

**Comment by LiJunnan1992** [comment]
Hi, training PCL for 200 epochs on ImageNet takes around 1 week with 4 V100 GPU.

**Comment by zwzhang123** [comment]
> Hi, training PCL for 200 epochs on ImageNet takes around 1 week with 4 V100 GPU.

okey, thanks.
