### ISSUE TITLE
Last prototype never sampled as negative

### ISSUE THREAD

**Issue by xiaotianliu-dartmouth** [salesforce/PCL#20]
https://github.com/salesforce/PCL/blob/15c090db2dcc03c46c709979fafe1f4b7266a4f6/pcl/builder.py#L178
In line 178 of PCL builder file,
`all_proto_id = [i for i in range(im2cluster.max())]`
does not include the id of the last prototype and hence the last prototype is never sampled as negative in this implementation.
Should be:
`all_proto_id = [i for i in range(im2cluster.max()+1)]`

**Comment by LiJunnan1992** [comment]
Thanks for pointing it out! I have updated the code accordingly.
