### ISSUE TITLE
about cifar10

### ISSUE THREAD

**Issue by Hiiragi0107** [salesforce/PCL#4]
Thank you for providing this code.
My question is: what is the optimal number of clusters to train on cifar10?

**Comment by LiJunnan1992** [comment]
Thanks for your interest.

I haven't experimented with cifar10, but I would assume over-clustering to be helpful, I would try 100<k<1000.

**Comment by Hiiragi0107** [comment]
Thanks for the reply.　:)

**Comment by aakash-saboo** [comment]
@Hiiragi0107 @LiJunnan1992 

Did you get the results for CIFAR10?
