### ISSUE TITLE
Hello, can I ask you about the accuracy of cifar-10, ImageNet100?

### ISSUE THREAD

**Issue by minkyujeon** [salesforce/PCL#7]
I experimented in cifar10, ImageNet100 in ResNet18 by using this code, but the accuracy of linear classifier is 
cifar10 : 82.77 (pcl_r : 512, num_cluster : [1000,2000,4000] / pcl_r 1024, num_cluster : [1500,3000,4500])
ImageNet100 : 64.40 (pcl_r : 1024, num_cluster : [2500,5000,10000] / pcl_r : 4096, num_cluster : [6000,8000,12000])

Even I adjusted the hyper-parameter, It can not be achieved other method's performance (byol, etc..). If you know the reason, could you tell me why? Thank you

**Comment by LiJunnan1992** [comment]
Hi, could you get good performance with moco? PCL can be built on-top-of existing SSL methods by adding the clustering loss, so it could be better to start with a set of hyper-parameters that is good for moco or simclr.

**Comment by minkyujeon** [comment]
Okay I'll check it. Thank you for replying!

**Comment by aakash-saboo** [comment]
@JeonMinkyu 
What were the final results you got on CIFAR10? and what config did you use? also did you use SIMCLR or MOCO?
