### ISSUE TITLE
inconsistency between the InfoNCE's negative samples and its corresponding clusters

### ISSUE THREAD

**Issue by ChangLee0903** [salesforce/PCL#8]
Hi, 

I very much appreciate this work, and thank you for providing the implementation code. I noticed that your implementation of InfoNCE loss is from the original MoCo repository, whose negative samples are determined by the key queue. According to the description, "instance discrimination task can be explained as a special case of prototypical contrastive learning," the two samples that belong to the same cluster can't be considered as a negative pair. But after tracing your code, I think the queue samples which cluster is the same as the query ones would be taken as negative pairs in InfoNCE. Have you tried to take the same cluster queue samples as positive?

best,
Chi-Chang Lee.

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest in PCL! Yes you are correct that such cases may happen. But since we use a large number of clusters, it would not happen frequently thus we ignore that.

**Comment by ChangLee0903** [comment]
Thanks for your response, I got it. No more questions.
